/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auctions from "../auctions.js";
import type * as cards from "../cards.js";
import type * as games from "../games.js";
import type * as messages from "../messages.js";
import type * as players from "../players.js";
import type * as swaps from "../swaps.js";
import type * as system from "../system.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auctions: typeof auctions;
  cards: typeof cards;
  games: typeof games;
  messages: typeof messages;
  players: typeof players;
  swaps: typeof swaps;
  system: typeof system;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
