import type { Metadata } from "next";
import React from "react";
import "@/styles/global.scss";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import LogoOverlay from "@/components/LogoOverlay/LogoOverlay";
export const metadata: Metadata = {
  title: "mono",
  description: "Generated by lldan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="ru"
        style={{
          colorScheme: "dark",
        }}
      >
        <body>
          <ConvexClientProvider>
            <LogoOverlay>{children}</LogoOverlay>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
